Updated test to pass again!

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -28,19 +28,7 @@ jobs:
 
       - name: Execute tests
         run: |
-          if [ -e "./tests/test_main.c" ]; then 
-            make all
-            test_log=$(./build/PlanckUnit)
-            echo "Test log:"
-            echo "$test_log"  # Print the entire test log
-            if [[ $test_log == *"FAILURE"* ]]; then
-              echo "Test log contains FAILURE. Exiting with code 1."
-              exit 1
-            else
-              echo "Test log does not contain FAILURE. Continuing."
-              exit 0
-            fi
-          fi
+          if [ -e "./tests/test_main.c" ]; then make all; test_log=$(./build/PlanckUnit); echo "Test log:"; echo "$test_log"; [[ $test_log == *"FAILURE"* ]] && { echo "Test log contains FAILURE. Exiting with code 1."; exit 1; } || { echo "Test log does not contain FAILURE. Continuing."; exit 0; }; fi
           
       - name: Send binary
         run: |
